#!/usr/bin/env bash
# Information about subdomains

if [ $# -eq 1 ]; then subdom=("www" "lb-01" "web-01" "web-02"); else subdom=("$2"); fi

function rlly {
	for sub in "${subdom[@]}";
	do
		dig "$sub.$1" | awk -v domi="$sub" '/ANSWER SECTION:/ { getline; print "The subdomain", domi, "is a", $4, "record and points to", $5}'
	done
}
rlly $1
