#!/usr/bin/env bash
#Instal and config haproxy
apt -y update
apt -y install software-properties-common
apt -y install haproxy
echo "frontend load_balancer
	bind *:80
	mode http
	default_backend lilium

backend lilium
	balance roundrobin
	server lilium1 34.75.178.156:0 check
	server lilium2 35.231.231.185:0 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
