#!/usr/bin/env bash
#THis prints 10 times and at the 4th and 8th different thingies
while((i++ < 10)); do if [ $i == 4 ]; then echo "bad luck"; elif [ $i == 8 ]; then echo "good luck"; else echo "Holberton School"; fi; done
